# Generated by Django 3.2 on 2021-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tg_user_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
