# Generated by Django 3.2 on 2021-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(to='catalog.Product_type'),
        ),
    ]
